apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab-pg
  namespace: cnpg-system
spec:
  instances: 2
  storage:
    storageClass: longhorn
    size: 5Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"
  postgresql:
    parameters:
      shared_buffers: "256MB"
  bootstrap:
    initdb:
      database: postgres
